title: Rain Doing Tech
author: rain
subtitle: The life of a frustrated engineer

url: 'https://danhmanh.github.io'
baseurl: ''

footer_only_homepage: true
footer_text: "Made by rain with love 🥰"

profile-picture: assets/profile.jpg
# profile-picture: assets/p1.jpg
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
  style: compressed
  sass_dir: css

navbar:
  - name: 'About'
    link: 'about'
  - name: 'Contact'
    link: 'contact'

plugins:
  - jekyll-toc